"""GENERATED by scripts/gen_tool_args.py from data/schemas/suryodaya/mcp-tools.json.
Do not edit. One <Tool>Input model per tool named in email_agent/skills/*/SKILL.md.
Serialise with model_dump(exclude_unset=True) — update models carry schema defaults.
"""
# generated by datamodel-codegen:
#   filename:  <dict>

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, EmailStr, Field, RootModel, conint, constr


class Risk(StrEnum):
    read = 'read'
    write = 'write'
    destructive = 'destructive'


class ToolsSearchInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: constr(min_length=1) = Field(
        ..., description='Words or an abbreviation (PO, WO, QI, MR).'
    )
    module: constr(min_length=1) | None = Field(
        None, description='Restrict to one module, e.g. manufacturing.'
    )
    risk: Risk | None = Field(None, description="Restrict by the tool's risk class.")
    limit: conint(ge=1, le=50) | None = 25


class ToolsSearchOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: str
    results: Any


class Name(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class ToolsDescribeInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    names: list[Name] = Field(
        ...,
        description='Tool names, e.g. from tools.search.',
        max_length=50,
        min_length=1,
    )


class ToolsDescribeOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: str
    results: Any


class SortOrder(StrEnum):
    asc = 'asc'
    desc = 'desc'


class ConnectionStatus(StrEnum):
    not_configured = 'not_configured'
    connected = 'connected'
    oauth_expired = 'oauth_expired'
    password_invalid = 'password_invalid'
    quota_exceeded = 'quota_exceeded'
    host_unreachable = 'host_unreachable'
    disabled = 'disabled'
    demo = 'demo'


class MailboxListInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limit: conint(ge=0, le=1000) | None = 20
    offset: conint(ge=0) | None = 0
    sort_by: str | None = None
    sort_order: SortOrder | None = 'desc'
    search: str | None = None
    display_name: str | None = None
    is_default: bool | None = False
    is_active: bool | None = True
    sync_state: str | None = None
    last_synced_at: date | None = None
    connection_status: ConnectionStatus | None = 'not_configured'
    last_status_change_at: date | None = None
    last_status_message: str | None = None
    consecutive_failures: float | None = 0
    next_retry_at: date | None = None


class Datum(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)


class MailboxListOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[Datum]
    total: conint(ge=0)
    limit: conint(ge=0)
    offset: conint(ge=0)


class StarType(StrEnum):
    star = 'star'
    red_star = 'red-star'
    orange_star = 'orange-star'
    green_star = 'green-star'
    blue_star = 'blue-star'
    purple_star = 'purple-star'
    red_bang = 'red-bang'
    orange_guillemet = 'orange-guillemet'
    yellow_bang = 'yellow-bang'
    green_check = 'green-check'
    blue_info = 'blue-info'
    purple_question = 'purple-question'
    red_flag = 'red-flag'
    orange_flag = 'orange-flag'
    yellow_flag = 'yellow-flag'
    green_flag = 'green-flag'
    blue_flag = 'blue-flag'
    purple_flag = 'purple-flag'
    gray_flag = 'gray-flag'


class Folder(StrEnum):
    inbox = 'inbox'
    sent = 'sent'
    drafts = 'drafts'
    trash = 'trash'
    spam = 'spam'
    archive = 'archive'
    snoozed = 'snoozed'
    scheduled = 'scheduled'
    outbox = 'outbox'


class SplitCategory(StrEnum):
    important = 'important'
    team = 'team'
    vip = 'vip'
    news = 'news'
    social = 'social'
    other = 'other'


class InferenceClass(StrEnum):
    focused = 'focused'
    other = 'other'


class Importance(StrEnum):
    low = 'low'
    normal = 'normal'
    high = 'high'


class FlagStatus(StrEnum):
    not_flagged = 'not_flagged'
    flagged = 'flagged'
    complete = 'complete'


class EmailThreadListInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limit: conint(ge=0, le=1000) | None = 20
    offset: conint(ge=0) | None = 0
    sort_by: str | None = None
    sort_order: SortOrder | None = 'desc'
    search: str | None = None
    company_id: constr(min_length=1) | None = None
    subject: str | None = None
    mailbox_id: constr(min_length=1) | None = None
    external_thread_id: str | None = None
    participant_emails: str | None = None
    participant_names: str | None = None
    message_count: float | None = 0
    unread_count: float | None = 0
    last_message_at: date | None = None
    last_sender_email: str | None = None
    last_sender_name: str | None = None
    snippet: str | None = None
    has_attachments: bool | None = False
    total_attachment_count: float | None = 0
    total_size_bytes: float | None = 0
    is_read: bool | None = False
    is_starred: bool | None = False
    star_type: StarType | None = None
    is_pinned: bool | None = False
    is_muted: bool | None = False
    folder: Folder | None = None
    labels: str | None = None
    split_category: SplitCategory | None = None
    inference_class: InferenceClass | None = None
    importance: Importance | None = None
    flag_status: FlagStatus | None = None
    flag_due_date: date | None = None
    party_id: constr(min_length=1) | None = None
    deal_id: constr(min_length=1) | None = None
    summary: str | None = None
    summary_updated_at: date | None = None
    snoozed_until: date | None = None


class EmailThreadListOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[Datum]
    total: conint(ge=0)
    limit: conint(ge=0)
    offset: conint(ge=0)


class Sensitivity(StrEnum):
    normal = 'normal'
    personal = 'personal'
    private = 'private'
    confidential = 'confidential'


class ReminderCondition(StrEnum):
    always = 'always'
    no_reply = 'no_reply'


class Encryption(StrEnum):
    none = 'none'
    tls = 'tls'
    pgp = 'pgp'


class SpfResult(StrEnum):
    pass_ = 'pass'
    fail = 'fail'
    neutral = 'neutral'
    none = 'none'
    softfail = 'softfail'
    temperror = 'temperror'
    permerror = 'permerror'
    policy = 'policy'


class DkimResult(StrEnum):
    pass_ = 'pass'
    fail = 'fail'
    neutral = 'neutral'
    none = 'none'
    softfail = 'softfail'
    temperror = 'temperror'
    permerror = 'permerror'
    policy = 'policy'


class DmarcResult(StrEnum):
    pass_ = 'pass'
    fail = 'fail'
    neutral = 'neutral'
    none = 'none'
    softfail = 'softfail'
    temperror = 'temperror'
    permerror = 'permerror'
    policy = 'policy'


class AuthSummary(StrEnum):
    pass_ = 'pass'
    partial = 'partial'
    fail = 'fail'
    none = 'none'


class SmimeStatus(StrEnum):
    none = 'none'
    signed_unverified = 'signed_unverified'
    signed_valid = 'signed_valid'
    signed_invalid = 'signed_invalid'
    encrypted = 'encrypted'
    decrypted = 'decrypted'


class SourceProvider(StrEnum):
    gmail = 'gmail'
    outlook = 'outlook'
    zoho = 'zoho'
    yahoo = 'yahoo'
    apple = 'apple'
    protonmail = 'protonmail'
    fastmail = 'fastmail'
    stalwart = 'stalwart'
    other = 'other'


class EmailMessageListInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limit: conint(ge=0, le=1000) | None = 20
    offset: conint(ge=0) | None = 0
    sort_by: str | None = None
    sort_order: SortOrder | None = 'desc'
    search: str | None = None
    company_id: constr(min_length=1) | None = None
    message_id: str | None = None
    mailbox_id: constr(min_length=1) | None = None
    thread_id: constr(min_length=1) | None = None
    in_reply_to: str | None = None
    references: str | None = None
    from_email: EmailStr | None = None
    from_name: str | None = None
    to: str | None = None
    cc: str | None = None
    bcc: str | None = None
    subject: str | None = None
    body_text: str | None = None
    snippet: str | None = None
    folder: Folder | None = None
    server_folder: str | None = None
    local_state_version: float | None = 0
    synced_state_version: float | None = 0
    labels: str | None = None
    is_read: bool | None = False
    is_starred: bool | None = False
    star_type: StarType | None = None
    is_pinned: bool | None = False
    is_muted: bool | None = False
    is_draft: bool | None = False
    is_answered: bool | None = False
    is_forwarded: bool | None = False
    has_attachments: bool | None = False
    attachment_count: float | None = 0
    attachments: str | None = None
    size_bytes: float | None = 0
    importance: Importance | None = None
    sensitivity: Sensitivity | None = None
    split_category: SplitCategory | None = None
    inference_class: InferenceClass | None = None
    flag_status: FlagStatus | None = None
    flag_due_date: date | None = None
    flag_completed_date: date | None = None
    party_id: constr(min_length=1) | None = None
    campaign_recipient_id: constr(min_length=1) | None = None
    deal_id: constr(min_length=1) | None = None
    status: str | None = 'draft'
    snoozed_until: date | None = None
    scheduled_send_at: date | None = None
    send_payload: str | None = None
    send_attempt_count: float | None = 0
    last_send_error: str | None = None
    reminder_at: date | None = None
    reminder_condition: ReminderCondition | None = None
    read_receipt_enabled: bool | None = False
    delivery_receipt_enabled: bool | None = False
    first_read_at: date | None = None
    read_count: float | None = 0
    read_device: str | None = None
    encryption: Encryption | None = None
    pgp_signed: bool | None = False
    has_tracking_pixels: bool | None = False
    tracking_pixels_blocked: bool | None = True
    phishing_score: float | None = 0
    phishing_reasons: str | None = None
    phishing_model: str | None = None
    dest_isp: str | None = None
    recipient_count: float | None = 0
    send_session_country: str | None = None
    spam_score: float | None = 0
    raw_headers: str | None = None
    list_unsubscribe: str | None = None
    spf_result: SpfResult | None = 'none'
    dkim_result: DkimResult | None = 'none'
    dmarc_result: DmarcResult | None = 'none'
    auth_summary: AuthSummary | None = 'none'
    smime_status: SmimeStatus | None = 'none'
    smime_signer_email: EmailStr | None = None
    sent_at: date | None = None
    received_at: date | None = None
    deleted_at: date | None = None
    source_provider: SourceProvider | None = None
    source_labels: str | None = None
    source_uid: str | None = None


class EmailMessageListOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[Datum]
    total: conint(ge=0)
    limit: conint(ge=0)
    offset: conint(ge=0)


class EmailThreadGetInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)


class EmailThreadGetOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)


class EmailThreadUpdateInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    company_id: constr(min_length=1) | None = None
    subject: str | None = None
    mailbox_id: constr(min_length=1) | None = None
    external_thread_id: str | None = None
    participant_emails: str | None = None
    participant_names: str | None = None
    message_count: float | None = 0
    unread_count: float | None = 0
    last_message_at: (
        constr(
            pattern=r'^\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2}(:\d{2}(\.\d{1,6})?)?(Z|[+-]\d{2}(:?\d{2})?)?)?$'
        )
        | None
    ) = None
    last_sender_email: str | None = None
    last_sender_name: str | None = None
    snippet: str | None = None
    has_attachments: bool | None = False
    total_attachment_count: float | None = 0
    total_size_bytes: float | None = 0
    is_read: bool | None = False
    is_starred: bool | None = False
    star_type: StarType | None = None
    is_pinned: bool | None = False
    is_muted: bool | None = False
    folder: Folder | None = None
    labels: str | None = None
    split_category: SplitCategory | None = None
    inference_class: InferenceClass | None = None
    importance: Importance | None = None
    flag_status: FlagStatus | None = None
    flag_due_date: date | None = None
    party_id: constr(min_length=1) | None = None
    deal_id: constr(min_length=1) | None = None
    summary: str | None = None
    summary_updated_at: (
        constr(
            pattern=r'^\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2}(:\d{2}(\.\d{1,6})?)?(Z|[+-]\d{2}(:?\d{2})?)?)?$'
        )
        | None
    ) = None
    snoozed_until: date | None = None


class EmailThreadUpdateOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)


class Category(StrEnum):
    preference = 'preference'
    fact = 'fact'
    instruction = 'instruction'
    context = 'context'
    relationship = 'relationship'


class Source(StrEnum):
    extracted = 'extracted'
    manual = 'manual'
    system = 'system'


class AgentMemoryCreateInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    party_id: constr(min_length=1) | None = None
    session_id: constr(min_length=1) | None = None
    category: Category | None = None
    content: str
    importance: float | None = None
    is_active: bool | None = True
    expires_at: (
        constr(
            pattern=r'^\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2}(:\d{2}(\.\d{1,6})?)?(Z|[+-]\d{2}(:?\d{2})?)?)?$'
        )
        | None
    ) = None
    source: Source | None = None
    company_id: constr(min_length=1) | None = None
    user_id: str | None = None


class AgentMemoryCreateOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)


class Type(StrEnum):
    snooze = 'snooze'
    follow_up = 'follow_up'
    scheduled_send = 'scheduled_send'


class Condition(StrEnum):
    always = 'always'
    no_reply = 'no_reply'


class EmailReminderCreateInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    company_id: constr(min_length=1)
    message_id: constr(min_length=1)
    thread_id: constr(min_length=1) | None = None
    type: Type
    remind_at: constr(pattern=r'^\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2}(:\d{2}(\.\d{1,6})?)?(Z|[+-]\d{2}(:?\d{2})?)?)?$')
    condition: Condition | None = None
    is_fired: bool | None = False
    fired_at: (
        constr(
            pattern=r'^\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2}(:\d{2}(\.\d{1,6})?)?(Z|[+-]\d{2}(:?\d{2})?)?)?$'
        )
        | None
    ) = None
    note: str | None = None


class EmailReminderCreateOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)


class EmailReminderListInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limit: conint(ge=0, le=1000) | None = 20
    offset: conint(ge=0) | None = 0
    sort_by: str | None = None
    sort_order: SortOrder | None = 'desc'
    search: str | None = None
    company_id: constr(min_length=1) | None = None
    message_id: constr(min_length=1) | None = None
    thread_id: constr(min_length=1) | None = None
    type: Type | None = None
    remind_at: date | None = None
    condition: Condition | None = None
    is_fired: bool | None = False
    fired_at: date | None = None
    note: str | None = None


class EmailReminderListOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[Datum]
    total: conint(ge=0)
    limit: conint(ge=0)
    offset: conint(ge=0)


class DealGetInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)


class DealGetOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)


class AgentMemoryListInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limit: conint(ge=0, le=1000) | None = 20
    offset: conint(ge=0) | None = 0
    sort_by: str | None = None
    sort_order: SortOrder | None = 'desc'
    search: str | None = None
    party_id: constr(min_length=1) | None = None
    session_id: constr(min_length=1) | None = None
    category: Category | None = None
    importance: float | None = None
    is_active: bool | None = True
    expires_at: date | None = None
    source: Source | None = None
    company_id: constr(min_length=1) | None = None
    user_id: str | None = None


class AgentMemoryListOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[Datum]
    total: conint(ge=0)
    limit: conint(ge=0)
    offset: conint(ge=0)


class BlockedReason(StrEnum):
    hard_bounce = 'hard_bounce'
    complaint = 'complaint'
    manual = 'manual'
    spam_trap = 'spam_trap'


class EmailContactListInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limit: conint(ge=0, le=1000) | None = 20
    offset: conint(ge=0) | None = 0
    sort_by: str | None = None
    sort_order: SortOrder | None = 'desc'
    search: str | None = None
    email: EmailStr | None = None
    name: str | None = None
    party_id: constr(min_length=1) | None = None
    company_id: constr(min_length=1) | None = None
    frequency: float | None = 0
    last_sent_at: date | None = None
    last_received_at: date | None = None
    is_vip: bool | None = False
    is_blocked: bool | None = False
    blocked_reason: BlockedReason | None = None
    blocked_at: date | None = None
    avatar_url: str | None = None
    domain: str | None = None
    user_id: str | None = None
    phone: str | None = None
    organization: str | None = None
    job_title: str | None = None
    notes: str | None = None


class EmailContactListOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[Datum]
    total: conint(ge=0)
    limit: conint(ge=0)
    offset: conint(ge=0)


class EmailMessageGetInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)


class EmailMessageGetOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)


class PartyGetInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)


class PartyGetOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)


class Salutation(StrEnum):
    Mr_ = 'Mr.'
    Mrs_ = 'Mrs.'
    Ms_ = 'Ms.'
    Dr_ = 'Dr.'
    Prof_ = 'Prof.'


class Type2(StrEnum):
    individual = 'individual'
    organization = 'organization'


class GstTreatment(StrEnum):
    business_gst = 'business_gst'
    business_composition = 'business_composition'
    consumer = 'consumer'
    overseas = 'overseas'
    unregistered_business = 'unregistered_business'
    sez = 'sez'
    deemed_export = 'deemed_export'


class ContactType(StrEnum):
    customer = 'customer'
    vendor = 'vendor'
    both = 'both'


class CustomerSubType(StrEnum):
    business = 'business'
    individual = 'individual'


class MsmeType(StrEnum):
    micro = 'micro'
    small = 'small'
    medium = 'medium'


class UsTaxClassification(StrEnum):
    individual_sole_proprietor = 'individual_sole_proprietor'
    c_corporation = 'c_corporation'
    s_corporation = 's_corporation'
    partnership = 'partnership'
    trust_estate = 'trust_estate'
    llc_c_corp = 'llc_c_corp'
    llc_s_corp = 'llc_s_corp'
    llc_partnership = 'llc_partnership'
    other = 'other'


class TinType(StrEnum):
    ssn = 'ssn'
    ein = 'ein'
    itin = 'itin'
    atin = 'atin'


class Form1099Type(StrEnum):
    field_1099_NEC = '1099-NEC'
    field_1099_MISC = '1099-MISC'


class Form1099Box(StrEnum):
    NEC_1 = 'NEC-1'
    MISC_1 = 'MISC-1'
    MISC_2 = 'MISC-2'
    MISC_3 = 'MISC-3'
    MISC_5 = 'MISC-5'
    MISC_6 = 'MISC-6'
    MISC_10 = 'MISC-10'
    MISC_14 = 'MISC-14'


class PartyListInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    limit: conint(ge=0, le=1000) | None = 20
    offset: conint(ge=0) | None = 0
    sort_by: str | None = None
    sort_order: SortOrder | None = 'desc'
    search: str | None = None
    company_id: constr(min_length=1) | None = None
    name: str | None = None
    customer_code: str | None = None
    salutation: Salutation | None = None
    first_name: str | None = None
    last_name: str | None = None
    type: Type2 | None = None
    email: EmailStr | None = None
    phone: str | None = None
    image: str | None = None
    birthday: date | None = None
    anniversary: date | None = None
    nickname: str | None = None
    pronouns: str | None = None
    job_title: str | None = None
    prefix: str | None = None
    suffix: str | None = None
    photo_url: str | None = None
    vcard_uid: str | None = None
    vcard_rev: str | None = None
    gst_treatment: GstTreatment | None = None
    place_of_supply: str | None = None
    credit_limit: float | None = None
    payment_terms: float | None = None
    payment_terms_label: str | None = None
    company_name: str | None = None
    contact_type: ContactType | None = None
    customer_sub_type: CustomerSubType | None = None
    currency_id: str | None = 'locale:base_currency'
    opening_balance: float | None = 0
    portal_enabled: bool | None = False
    is_portal_enabled: bool | None = False
    website: str | None = None
    facebook: str | None = None
    twitter: str | None = None
    taxable: bool | None = True
    tax_name: str | None = None
    tax_exemption_reason: str | None = None
    owner_name: str | None = None
    msme_type: MsmeType | None = None
    is_msme: bool | None = False
    vendor_bank_name: str | None = None
    vendor_bank_code: str | None = None
    us_tax_classification: UsTaxClassification | None = None
    tin_type: TinType | None = None
    w9_on_file: bool | None = False
    w9_received_date: date | None = None
    is_1099_vendor: bool | None = False
    form_1099_type: Form1099Type | None = None
    form_1099_box: Form1099Box | None = None
    exempt_payee_code: str | None = None
    fatca_exemption_code: str | None = None
    backup_withholding: bool | None = False


class PartyListOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[Datum]
    total: conint(ge=0)
    limit: conint(ge=0)
    offset: conint(ge=0)

# Tool name → its arguments model (used by email_agent/action.py to validate every call).
TOOL_ARGS: dict[str, type[BaseModel]] = {
    'tools.search': ToolsSearchInput,
    'tools.describe': ToolsDescribeInput,
    'Mailbox.list': MailboxListInput,
    'EmailThread.list': EmailThreadListInput,
    'EmailMessage.list': EmailMessageListInput,
    'EmailThread.get': EmailThreadGetInput,
    'EmailThread.update': EmailThreadUpdateInput,
    'AgentMemory.create': AgentMemoryCreateInput,
    'EmailReminder.create': EmailReminderCreateInput,
    'EmailReminder.list': EmailReminderListInput,
    'Deal.get': DealGetInput,
    'AgentMemory.list': AgentMemoryListInput,
    'EmailContact.list': EmailContactListInput,
    'EmailMessage.get': EmailMessageGetInput,
    'Party.get': PartyGetInput,
    'Party.list': PartyListInput,
}
